### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by HrysiukDmytro** [porta-network/porta-node#10]
Nov 22 20:24:37 porta porta[49612]:    7: std::panicking::try
Nov 22 20:24:37 porta porta[49612]:    8: environmental::using
Nov 22 20:24:37 porta porta[49612]:    9: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
Nov 22 20:24:37 porta porta[49612]:   10: sc_executor::wasm_runtime::RuntimeCache::with_instance
Nov 22 20:24:37 porta porta[49612]:   11: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
Nov 22 20:24:37 porta porta[49612]:   12: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
Nov 22 20:24:37 porta porta[49612]:   13: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
Nov 22 20:24:37 porta porta[49612]:   14: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
Nov 22 20:24:37 porta porta[49612]:   15: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Nov 22 20:24:37 porta porta[49612]:   16: sp_api::runtime_decl_for_Core::execute_block_call_api_at
Nov 22 20:24:37 porta porta[49612]:   17: sp_api::Core::execute_block_with_context
Nov 22 20:24:37 porta porta[49612]:   18: sc_service::client::client::Client<B,E,Block,RA>::prepare_block_storage_changes
Nov 22 20:24:37 porta porta[49612]:   19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Nov 22 20:24:37 porta porta[49612]:   20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Nov 22 20:24:37 porta porta[49612]:   21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Nov 22 20:24:37 porta porta[49612]:   22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Nov 22 20:24:37 porta porta[49612]:   23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Nov 22 20:24:37 porta porta[49612]:   24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Nov 22 20:24:37 porta porta[49612]:   25: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Nov 22 20:24:37 porta porta[49612]:   26: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Nov 22 20:24:37 porta porta[49612]:   27: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Nov 22 20:24:37 porta porta[49612]:   28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Nov 22 20:24:37 porta porta[49612]:   29: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Nov 22 20:24:37 porta porta[49612]:   30: futures_executor::local_pool::block_on
Nov 22 20:24:37 porta porta[49612]:   31: tokio::runtime::task::core::Core<T,S>::poll
Nov 22 20:24:37 porta porta[49612]:   32: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Nov 22 20:24:37 porta porta[49612]:   33: tokio::runtime::task::harness::Harness<T,S>::poll
Nov 22 20:24:37 porta porta[49612]:   34: tokio::runtime::blocking::pool::Inner::run
Nov 22 20:24:37 porta porta[49612]:   35: tokio::runtime::context::enter
Nov 22 20:24:37 porta porta[49612]:   36: std::sys_common::backtrace::__rust_begin_short_backtrace
Nov 22 20:24:37 porta porta[49612]:   37: core::ops::function::FnOnce::call_once{{vtable.shim}}
Nov 22 20:24:37 porta porta[49612]:   38: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Nov 22 20:24:37 porta porta[49612]:              at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636:9
Nov 22 20:24:37 porta porta[49612]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Nov 22 20:24:37 porta porta[49612]:              at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636:9
Nov 22 20:24:37 porta porta[49612]:       std::sys::unix::thread::Thread::new::thread_start
Nov 22 20:24:37 porta porta[49612]:              at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys/unix/thread.rs:106:17
Nov 22 20:24:37 porta porta[49612]:   39: start_thread
Nov 22 20:24:37 porta porta[49612]:   40: clone
Nov 22 20:24:37 porta porta[49612]: Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/70ef0af/frame/executive/src/lib.rs:462
Nov 22 20:24:37 porta porta[49612]: This is a bug. Please report it at:
Nov 22 20:24:37 porta porta[49612]:         https://github.com/porta-network/porta-node/issues/new
Nov 22 20:24:37 porta porta[49612]: 2021-11-22 20:24:37  ⚙️  Syncing 110.0 bps, target=#2474526 (50 peers), best: #646038 (0xa352…6a11), finalized #645672 (0x95ef…ce48), ⬇ 6.9kiB/s ⬆ 14.2kiB/s
Nov 22 20:24:39 porta porta[49612]: Hash: given=33a821c7b468c7bc66a1c53c69956392f868812be856cbad8133fe5a42167419, expected=26cc564c398b2c8d9c7dec9848c149d8bba578f0be16ad3c67cff216f31b4332
Nov 22 20:24:39 porta porta[49612]: ====================
Nov 22 20:24:39 porta porta[49612]: Version: 2.0.0-e3286eb-x86_64-linux-gnu

**Comment by HrysiukDmytro** [comment]
How it can be fixed?
