### ISSUE TITLE
found a bug

### ISSUE THREAD

**Issue by Sacadi** [porta-network/porta-node#5]
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]: Version: 2.0.0-e3286eb-x86_64-linux-gnu
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:    0: sp_panic_handler::set::{{closure}}
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:    1: std::panicking::rust_panic_with_hook
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:              at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:628:17
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:    2: std::panicking::begin_panic::{{closure}}
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:    4: std::panicking::begin_panic
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:    5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:    6: <porta_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,u32>,porta_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<porta_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<porta_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<porta_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<porta_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<porta_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<porta_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<porta_runtime::Runtime>)>>>>::execute_block
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:    7: std::panicking::try
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:    8: environmental::using
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:    9: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   10: sc_executor::wasm_runtime::RuntimeCache::with_instance
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   11: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   12: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   13: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   14: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   15: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   16: sp_api::runtime_decl_for_Core::execute_block_call_api_at
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   17: sp_api::Core::execute_block_with_context
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   18: sc_service::client::client::Client<B,E,Block,RA>::prepare_block_storage_changes
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   25: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   26: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   27: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   29: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   30: futures_executor::local_pool::block_on
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   31: tokio::runtime::task::core::Core<T,S>::poll
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   32: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   33: tokio::runtime::task::harness::Harness<T,S>::poll
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   34: tokio::runtime::blocking::pool::Inner::run
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   35: tokio::runtime::context::enter
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   36: std::sys_common::backtrace::__rust_begin_short_backtrace
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   37: core::ops::function::FnOnce::call_once{{vtable.shim}}
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   38: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:              at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/boxed.rs:1636:9
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:              at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/boxed.rs:1636:9
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:       std::sys::unix::thread::Thread::new::thread_start
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:              at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys/unix/thread.rs:106:17
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   39: start_thread
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:   40: clone
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]: Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/70ef0af/frame/executive/src/lib.rs:462
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]: This is a bug. Please report it at:
Oct 26 23:30:07 ubuntu-8gb-hel1-1 porta[47382]:         https://github.com/porta-network/porta-node/issues/new

**Comment by dbaida** [comment]
Looks similar to me: https://github.com/porta-network/porta-node/issues/4
